{{- if not (eq .Values.createSecret false) -}}
{{- $namespace := .Values.namespace | default .Release.Namespace -}}
{{- $name := .Values.fullnameOverride | default .Chart.Name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-secret
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/part-of: {{ $.Values.global.partOf | default "fanvault" }}
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.auth.username | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.auth.password | quote }}
  RABBITMQ_ERLANG_COOKIE: {{ .Values.auth.erlangCookie | quote }}
  RABBITMQ_DEFAULT_VHOST: {{ .Values.auth.vhost | default "/" | quote }}
{{- end }}
