apiVersion: v1
kind: Service
metadata:
  name: {{ include "microapp.name" . }}
  namespace: {{ include "microapp.namespace" . }}
  labels:
    {{- include "microapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "microapp.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
