nameOverride: email-service
namespace: dev
partOf: fanvault
component: backend
role: dev-backend
replicaCount: 1
image:
  repository: savitxr/fanvault-email
  tag: v0.0.1
  pullPolicy: IfNotPresent
containerPort: 3005
service:
  type: ClusterIP
  port: 3005
probes:
  liveness:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 20
    failureThreshold: 3
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop: [ALL]
