{{- if not (eq .Values.createSecret false) -}}
{{- $namespace := .Values.namespace | default .Release.Namespace -}}
{{- range .Values.instances }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-secret
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/part-of: {{ $.Values.global.partOf | default "fanvault" }}
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ $.Values.auth.rootUser | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ $.Values.auth.rootPassword | quote }}
{{- end }}
{{- end }}
